import Nav from "./components/Nav";
import Aside from "./components/Aside";
import "./globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Cyberavangelists",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <Aside>{children}</Aside>
      </body>
    </html>
  );
}
